### ISSUE TITLE
restrictive question

### ISSUE THREAD

**Issue by fantast1211** [unruhe73/check-mysql-db-structure#1]
Hello author, I would like to ask, is this tool only able to compare a single table in a single database? If the sql file contains multiple statements for creating tables, can it be used?

**Comment by fantast1211** [comment]
I'm sorry, I didn't read the code carefully just now

**Comment by unruhe73** [comment]
You didn't need to read the code carefully. It's written in the README.md file: «This project is a tool to compare two MySQL or MariaDB *databases structure* showing these details in form of text in a terminal, or writing them into a log file as you prefer. This tool is available by the python class CheckMySQLDB».

**Comment by unruhe73** [comment]
> I'm sorry, I didn't read the code carefully just now
You didn't need to read the code carefully. It's written in the README.md file: «This project is a tool to compare two MySQL or MariaDB databases structure showing these details in form of text in a terminal, or writing them into a log file as you prefer. This tool is available by the python class CheckMySQLDB».
